<script type="text/javascript">
    jQuery('#email_address').keyup(function (e) {
        clearTimeout(jQuery.data(this, 'timer'));
        jQuery(this).data('timer', setTimeout(validate, 100));
    });

    function validate() {
        let email = jQuery('#email_address').val();
        jQuery.post('<?php echo $this->getUrl('zerobounce/index/index') ?>',
            {email: email, isAjax: true},
            function (data) {
                data = jQuery.parseJSON(data);
                if (data.status == 'invalid') {
                    if (jQuery('.validation-advice').remove()) {
                        jQuery('.validation-advice').remove();
                    }
                    jQuery('#email_address').after('<div class="validation-advice" id="email-error">' + data.message + '</div>');
                }
            }
        )
    }

</script>